# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined', models.ManyToManyField(related_name='joined_courses', to='LogReg.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='LogReg.User')),
            ],
        ),
    ]
